### PR TITLE
Pull request [Translation]

### PR DESCRIPTION
**Pull request by atomicf4ll**
So I've translated the whole plugin to the Czech language. Hope you will add it to the plugin soon :)

### CODE REVIEW

**Comment by VerdiH** [comment]
@atomicf4ll Thank you very much for your work, we hope this will benefit many Czech speakers. Na zdraví!

**Comment by sheabunge** [comment]
Thank you @atomicf4ll!

We'd love to credit you in the readme, if that's okay with you. Is there a name and website URL you'd like us to use?

**Comment by atomicf4ll** [comment]
Oh, sorry, just forgot to answer. It would be a pleasure for me to be in credits. As for name, please use "Lukáš Tesař". Since I have no website yet, perhaps you can use my email instead (lukastesar03@gmail.com)?

**Comment by sheabunge** [comment]
Of course, will do. Thanks again!

**Pull request merged**
